### ISSUE TITLE
Error in XMLDOM

### ISSUE THREAD

**Issue by markuplab** [Pavliko/postcss-svg#24]
After last update, i got this error:

```
  TypeError: node.serializeToString is not a function
      at XMLSerializer.serializeToString (/Users/k.kaysarov/src/account/node_modules/xmldom/dom.js:906:7)
      at SVGImage._addSprite (/Users/k.kaysarov/src/account/node_modules/postcss-svg/dist/lib/svg_image.js:199:40)
      at SVGImage._parseNode (/Users/k.kaysarov/src/account/node_modules/postcss-svg/dist/lib/svg_image.js:143:20)
      at SVGImage._parseNode (/Users/k.kaysarov/src/account/node_modules/postcss-svg/dist/lib/svg_image.js:148:16)
      at SVGImage._parseSvg (/Users/k.kaysarov/src/account/node_modules/postcss-svg/dist/lib/svg_image.js:99:18)
      at new SVGImage (/Users/k.kaysarov/src/account/node_modules/postcss-svg/dist/lib/svg_image.js:31:12)
      at Object.module.exports.addToIndex (/Users/k.kaysarov/src/account/node_modules/postcss-svg/dist/lib/svg_cache.js:65:15)
      at Object.module.exports.init (/Users/k.kaysarov/src/account/node_modules/postcss-svg/dist/lib/svg_cache.js:25:14)
      at /Users/k.kaysarov/src/account/node_modules/postcss-svg/dist/index.js:24:16
      at LazyResult.run (/Users/k.kaysarov/src/account/node_modules/css-modules-loader-core/node_modules/postcss/lib/lazy-result.js:201:20)
```

I look on xmldom and it was updated today. 
https://github.com/jindw/xmldom/commit/2d3c3dbb0a561e916f53fccfa02d8df5f6a9c89f

**Comment by jonathantneal** [comment]
This plugin now uses xmldoc 1.1.0 :) https://github.com/Pavliko/postcss-svg#readme
